// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://perumoutkkebtktsqatq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcnVtb3V0a2tlYnRrdHNxYXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDM0ODcsImV4cCI6MjA1ODU3OTQ4N30.-gFhWDgKSGPxmEbqmQZr6i0d5pCzH43F9wr3pgwDmzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});